image: golangci/golangci-lint:v1.42.0

.go-cache:
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
    cache:
      paths:
        - .go/pkg/mod/

before_script:
  - echo "before_script"
  - echo "set go env"
  - export GOPROXY=https://goproxy.cn,direct

stages:
    - lint

golangci-lint:
    image: golangci/golangci-lint:v1.42.0
    stage: lint
    extends: .go-cache
    allow_failure: false
    script:
      - golangci-lint run -v -E golint -E goimports -E govet --timeout 10m
